### PR TITLE
Add HMR decline when using `solid-refresh` in non-dev env

### PR DESCRIPTION
**Pull request by lxsmnsyc**
Thanks to @edemaine for his effort. This PR intends to override his PR: https://github.com/solidjs/solid-refresh/pull/11 so that the code is generated by Babel instead of the library. The reason we want to do this is because 1) the initial solution do not work for ESM/Vite HMR and 2) Some standard HMR implementations do not have `decline`. The babel already has a utility function to generate a safe `decline` code if the bundler happens to not support it.

<s>The warning code follows the original implementation however it doesn't have a one-time flag to set with. I'm not sure if we should utilize `globalThis`.</s>

### CODE REVIEW

**Comment by edemaine** [comment]
This looks great to me! Perhaps you could also copy over the small change to the README from https://github.com/solidjs/solid-refresh/pull/11/files?

**Comment by LXSMNSYC** [comment]
> This looks great to me! Perhaps you could also copy over the small change to the README from https://github.com/solidjs/solid-refresh/pull/11/files?

Right, I forgot about that one 😅

**Comment by ryansolid** [comment]
Is this time to merge? Sorry just not following this issue. Are we happy?

**Comment by lxsmnsyc** [comment]
Yeah this should be good. I'll probably just re-bump the dependencies on a new PR

**Pull request merged**
