### PR TITLE
Feature: Granular Update, part 2

### PR DESCRIPTION
**Pull request by LXSMNSYC**
Changes:
- Adds `dependencies` to hot registrations and signatures. This allows foreign binding detections and compares them on module reload, prompting a remount if the dependencies change (You can think of this as React's useEffect). This is useful to detect if the component signature is unchanged (meaning no code change) but the dependencies changed. This currently evaluates any identifier expressions and jsx member expressions' object as valid bindings and crawls upwards the scope to detect if it doesn't belong in the root scope.
- Partially restructured signature construction, this is to potentially make the output code smaller.
- Fixes error for nested/compositional components. The error occurs due to a missing `set` handler for the `Proxy` wrapper. It tries to read from the original source however the `Proxy` writes properties to its new source.
- ~~Add `@refresh local-skip`: Make component opt-out of HMR processing~~
- ~~Add `@refresh local-granular`: Make component opt-in to granular reloading (this is similar to `@refresh granular` except that it's component-based).~~
- ~~Add `@refresh local-reload`: Prompt a full page reload if a component changes (similar to `@refresh reload` except that it only checks for an specific component change).~~
- Adds snapshot testing
- `"vite"` bundler mode no longer normalizes to `"esm"` mode due to differing interpretations of `import.meta.hot.accept`.
- Added `module.hot.decline` compat for Parcel and Nollup
- `"esm"` and `"vite"` accept handler can now return `true` for module invalidation. This changes how `import.meta.hot.accept` code is also generated.

Tested with:
- [x] Vite
- [x] Parcel 2
- [x] Webpack (possibly solved by Parcel test)
- [x] Nollup (possibly solved by Parcel test)
- [ ] ~~Rollup (through rollup-plugin-hot) (possibly solved by Vite test)~~ Has non-standard ESM HMR
- [ ] Snowpack (possibly solved by Vite test)

Todo
- Rewrite the README

Question:
- At this point, if granular mode does not pose any issues, should this be the default behavior now? Being not the default behavior is still okay.

~~Some unexpected behavior~~
- ~~When opting-in to `@refresh local-skip` after module reload, `esm` invalidates the module while `standard` does not do anything and would require manual reload. The reason is `local-skip` does not generate any `hot` component (this is both true to `esm` and `standard`) however `standard` re-evaluates the same module which is unlike `esm` HMR whose original module persists.~~

### CODE REVIEW

**Comment by LXSMNSYC** [comment]
For those who wants to test:

```bash
npm install solid-refresh@npm:@lxsmnsyc/solid-refresh@^0.3.8
```

Webpack, Nollup are the important ones to test with, specially for the side-effect testing and the nested components testing.

I'm pretty curious if we should write something of a per-bundler (webpack, parcel) mode instead of per-hmr (esm, standard) mode just to strictly cover some bundler differences as well as to optimize the code.

**Comment by LXSMNSYC** [comment]
Tested with Webpack and Nollup. Snowpack and rollup-plugin-hot should be minor concerns.

**Comment by ryansolid** [comment]
That looks good to me. Are we ready?

I think we merge this with granular as opt in test it for a bit in the wild and then move to another minor version where this is the default behavior.

**Comment by LXSMNSYC** [comment]
I'm still yet unsure if `local-skip` has a role. It behaves differently when in granular mode in contrast with default mode.

**Comment by ryansolid** [comment]
Do we need the `local-` at all? I wasn't really looking at this as an options thing initially. Just needed to solve a very specific problem with Document level hydration. I wrote skip initially so that I could manually handle Hot in the file, and then decided to build the reload mechanism after. I guess its nice to have that level of control but I also think its overkill. Like turn it on or turn it off for the file. Having the local switches introduces potentially different behaviors/combinations. If feels like just asking for trouble unless necessary.

**Comment by LXSMNSYC** [comment]
I could definitely justify those 3 when it comes to default mode, however, things behave differently when it comes to granular mode. If we decide to make the granular mode the default mode, we could totally remove these `local-` pragmas

**Comment by LXSMNSYC** [comment]
Okay I decided to just remove the local pragmas. Let me test this again.

**Comment by LXSMNSYC** [comment]
Added setup guides

**Comment by ryansolid** [comment]
> I could definitely justify those 3 when it comes to default mode, however, things behave differently when it comes to granular mode. If we decide to make the granular mode the default mode, we could totally remove these `local-` pragmas

Yeah I think we want to move to granular by default as soon as we feel comfortable. I think we aim for that. Unless you have any concerns?

**Comment by LXSMNSYC** [comment]
No concerns anymore, I removed it now since I do think the granular mode will be the default if we proved it effective.

**Pull request merged**
